Sprint 3
TheRealMagic/middle.messenger.praktikum.yandex pull request #14
Opened 2022-02-26 17:22 UTC by TheRealMagic

2022-02-26 18:43 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, все выглядит отлично, но к сожалению я не нашел в ней обработку ошибок в работу с асинхронными функциями. А это очень важная часть, обработать ошибку и проинформировать юзера, что что-то идет не так. Давайте это исправим)

2022-02-26 18:43 UTC, DmitryKhitrin commented on .mocharc.json
> +}
Для git важно, что бы файл заканчивался [пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-02-26 18:43 UTC, DmitryKhitrin commented on src/controllers/ChatsPageController.ts
> +  createSocket(chatId: number, token: string) {
Я бы предложил разделить логику создания и взаимодействия с вебсокетами и локгику работы чатов, так получится лучше разделить технический инструмент и бизнес логику

2022-02-26 18:43 UTC, DmitryKhitrin commented on src/controllers/SignUpPageController.ts
> +      signUpPageApi.register(data);
Тут должен быть await, без него try catch не поймает ошибку

2022-02-26 18:43 UTC, DmitryKhitrin commented on src/models/User.ts
> +    display_name?: string,
Часто удобно сверху описывать обязательные поля, снизу опциональные, хотя ваш вариант группировки по смыслу тоже отличный)

2022-02-26 18:43 UTC, khitrind commented on src/utils/API/BaseApi.ts
> +export class BaseAPI {
Как будто BaseAPI не нужен, вы же мало где имплементируете его методы

2022-02-26 18:43 UTC, DmitryKhitrin commented on src/utils/API/UserApi.ts
> +        if (result.status === 200) {
Эту проверку можно вынести в базовый HTTP и просто при не 200 статусе бросать reject

2022-02-26 18:43 UTC, khitrind commented on src/utils/API/index.ts
> +export {LoginPageApi};
```suggestion
export {LoginPageApi} from "./LoginPageApi";
```

2022-02-27 08:02 UTC, TheRealMagic commented on src/utils/API/BaseApi.ts
> +export class BaseAPI {
да, хотел сделать похоже на теорию, но получились разные классы апишек. Но я думаю что наследование стоит оставить для того, если потом потребуется добавить что-то общее в эти классы.
Методы удалил :)

2022-02-27 10:53 UTC, closed without merging