Sprint 4
TheRealMagic/middle.messenger.praktikum.yandex pull request #17
Opened 2022-03-13 18:13 UTC by TheRealMagic

2022-03-13 18:54 UTC, DmitryKhitrin requested changes
Привет, спасибо за вашу работу, сборка выглядит не плохо, но некоторые моменты хотелось бы поправить:

- использование docker образа с предустановленной node;
- я к сожалению не смог найти ссылку на heroku в readme (один из пунктов ТЗ);

2022-03-13 18:54 UTC, DmitryKhitrin commented on Dockerfile
> +FROM alpine:3.15
Для nodejs приложений, есть уже готовые контейнеры с предустановленной nodejs нужной версии. Данный образ поддерживает официальная команда [node](https://hub.docker.com/_/node)

2022-03-13 18:54 UTC, DmitryKhitrin commented on webpack.config.js
> +  mode: "development",
Для учебного приложения подойдет и такой вариант сборки но на будущее, обычно разделяют prod и dev вариации. В production сборку не попадают debug тулзы + код оптимизируется и минифицируется что качественно влияет на скорость загрузки и исполнения кода https://webpack.js.org/guides/production/

2022-03-13 18:54 UTC, DmitryKhitrin commented on webpack.config.js
> +};
Для git важно, что бы файл заканчивался [пустой строкой](https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log)

2022-03-13 21:28 UTC, TheRealMagic commented on Dockerfile
> +FROM alpine:3.15
при отладке пробовал и node сборку и alpine... Почему-то решил остановиться на alpine :)

Перед коммитом пересмотрел и задание к проектной работе и чек лист - не нашел пункта про ссылку на herocu, возможно пропустил

2022-03-13 21:28 UTC, TheRealMagic commented on webpack.config.js
> +  mode: "development",
да, читал про продакт сборку
возможно, реализую, как появится свободное время, если это не критично

2022-03-13 23:40 UTC, DmitryKhitrin requested changes
Привет, ссылки на heroku я по прежнему не смог найти, добавьте ее пожалуйста

2022-03-14 06:20 UTC, TheRealMagic commented
> Привет, ссылки на heroku я по прежнему не смог найти, добавьте ее пожалуйста

странно, добавил вчера в readme
Давай продублирую тут
https://docker-lesson-app.herokuapp.com/

![image](https://user-images.githubusercontent.com/78367550/158115879-ba2e6ac1-e993-4a70-b725-1dfb1a6d37f6.png)

2022-03-16 22:08 UTC, DmitryKhitrin approved these changes
Удачи в следующих спринтах)

2022-10-27 17:07 UTC, merged